# GoReleaser configuration
# Note: Cross-compilation is handled by GitHub Actions.
# For local development on Windows, use:
#   goreleaser build --single-target --snapshot --clean
version: 2

project_name: tree

before:
  hooks:
    - rustup default stable
    - cargo fetch --locked

builds:
  - builder: rust
    binary: tree
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
      - goos: darwin
        formats: [zip]
    files:
      - none*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  draft: true
  footer: |
    ---
    Released with [GoReleaser](https://github.com/goreleaser/goreleaser)

universal_binaries:
  - replace: true
