name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) title of the release
          title: tree Release ${{ github.ref_name }}
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: Linux-amd64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: Linux-arm64
          - target: x86_64-apple-darwin
            os: macos-latest
            name: macOS-amd64
          - target: aarch64-apple-darwin
            os: macos-latest
            name: macOS-arm64
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            name: Windows-64bit
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build and upload assets
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: tree
          # Customize archive name to use user-friendly platform names
          archive: tree-${{ github.ref_name }}-${{ matrix.name }}
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}

  windows-32bit:
    needs: create-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: i686-pc-windows-msvc

      - name: Build 32-bit Windows binary
        run: cargo build --release --target i686-pc-windows-msvc

      - name: Create zip archive
        shell: pwsh
        run: |
          Compress-Archive -Path "target/i686-pc-windows-msvc/release/tree.exe" -DestinationPath "tree-${{ github.ref_name }}-Windows-32bit.zip"

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tree-${{ github.ref_name }}-Windows-32bit.zip
          asset_name: tree-${{ github.ref_name }}-Windows-32bit.zip
          tag: ${{ github.ref }}
